{
  imports = [
    ./audio.nix
    ./bluetooth.nix
    ./boot.nix
    ./env.nix
    ./home-manager.nix
    ./gnome.nix
    ./hyprland.nix
    ./kernel.nix
    ./mime.nix
    ./net.nix
    ./nh.nix
    ./nix.nix
    ./timezone.nix
    ./user.nix
    ./zram.nix
    ./docker.nix
    ./printing.nix
    ./wine.nix
    ./vbox.nix
    ./qemu.nix
    ./sshd.nix
  ];
}
